import type { VideoReport, GitHubProject } from './types.js';

/**
 * Language-to-color mapping for badges.
 */
const LANG_COLORS: Record<string, string> = {
  TypeScript: '#3178c6',
  JavaScript: '#f1e05a',
  Python: '#3572A5',
  Rust: '#dea584',
  Go: '#00ADD8',
  Java: '#b07219',
  'C++': '#f34b7d',
  C: '#555555',
  'C#': '#178600',
  Ruby: '#701516',
  PHP: '#4F5D95',
  Swift: '#F05138',
  Kotlin: '#A97BFF',
  Dart: '#00B4AB',
  Shell: '#89e051',
  HTML: '#e34c26',
  CSS: '#563d7c',
  Scala: '#c22d40',
  Elixir: '#6e4a7e',
  Haskell: '#5e5086',
  Lua: '#000080',
  Zig: '#ec915c',
  Vue: '#41b883',
  Svelte: '#ff3e00',
};

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

function escapeAttr(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/\n/g, '&#10;');
}

function formatStars(stars: number | null): string {
  if (stars === null || stars === undefined) return '';
  return stars >= 1000 ? `${(stars / 1000).toFixed(1)}k` : String(stars);
}

/**
 * Generate an index page that lists all reports.
 */
export function generateIndexHtml(reports: Array<{ filename: string; title: string; date: string; projectCount: number; videoUrl: string }>): string {
  const items = reports.map(r => `
    <a class="report-card" href="${escapeHtml(r.filename)}">
      <div class="report-title">${escapeHtml(r.title)}</div>
      <div class="report-meta">
        <span>${escapeHtml(r.date)}</span>
        <span>·</span>
        <span>${r.projectCount} projects</span>
      </div>
    </a>`).join('\n');

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>GithubAwesome Monitor</title>
  <style>
    *{margin:0;padding:0;box-sizing:border-box}
    body{
      font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Helvetica,Arial,sans-serif;
      background:#0d1117;color:#c9d1d9;min-height:100vh;
    }
    .header{
      border-bottom:1px solid #21262d;
      padding:1.25rem 1rem;
      max-width:640px;margin:0 auto;
    }
    .header h1{color:#f0f6fc;font-size:1.15rem;font-weight:700;margin-bottom:0.15rem}
    .header p{color:#8b949e;font-size:0.8rem}
    .list{max-width:640px;margin:0 auto;padding:0.5rem 0}
    .report-card{
      display:block;
      padding:0.75rem 1rem;
      border-bottom:1px solid #21262d;
      text-decoration:none;
      color:inherit;
    }
    .report-card:last-child{border-bottom:none}
    .report-card:hover{background:#161b22}
    .report-title{color:#58a6ff;font-size:0.9rem;font-weight:600;margin-bottom:0.15rem}
    .report-meta{color:#8b949e;font-size:0.75rem;display:flex;gap:0.4rem;align-items:center}
    .footer{text-align:center;padding:1.5rem 1rem;color:#484f58;font-size:0.7rem;border-top:1px solid #21262d;margin-top:1rem}
  </style>
</head>
<body>
<div class="header">
  <h1>GithubAwesome Monitor</h1>
  <p>Trending projects from the GithubAwesome YouTube channel</p>
</div>
<div class="list">
${items}
</div>
<div class="footer">Generated by github-awesome-monitor</div>
</body>
</html>`;
}

/**
 * Generate a complete HTML page for a video report.
 * The summary text is truncated to 3 lines with a "show more" toggle.
 * All project data lives in a JSON blob so the page is fully self-contained.
 */
export function generateHtml(report: VideoReport): string {
  const date = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
  });

  // Escape </script> sequences in JSON to prevent breaking out of the HTML tag
  const projectsJson = JSON.stringify(report.projects).replace(/<\/script/gi, '<\\/script');
  const colorsJson = JSON.stringify(LANG_COLORS);

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(report.title)} — GithubAwesome Projects</title>
  <style>
    *{margin:0;padding:0;box-sizing:border-box}
    body{
      font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Helvetica,Arial,sans-serif;
      background:#0d1117;color:#c9d1d9;min-height:100vh;
    }
    .header{
      border-bottom:1px solid #21262d;
      padding:1.25rem 1rem;
      max-width:640px;margin:0 auto;
    }
    .header h1{color:#f0f6fc;font-size:1.15rem;font-weight:700;margin-bottom:0.25rem}
    .header .meta{display:flex;align-items:center;gap:0.5rem;flex-wrap:wrap;font-size:0.8rem;color:#8b949e}
    .header .meta a{color:#58a6ff;text-decoration:none}
    .header .meta a:hover{text-decoration:underline}
    .badge{background:#238636;color:#fff;font-size:0.7rem;padding:1px 8px;border-radius:9999px;font-weight:600}
    .list{max-width:640px;margin:0 auto;padding:0.5rem 0}
    .project{
      padding:0.75rem 1rem;
      border-bottom:1px solid #21262d;
    }
    .project:last-child{border-bottom:none}
    .project-top{display:flex;align-items:center;gap:0.35rem;margin-bottom:0.2rem;flex-wrap:wrap}
    .project-top a{color:#58a6ff;font-size:0.9rem;font-weight:600;text-decoration:none;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;max-width:100%}
    .project-top a:hover{text-decoration:underline}
    .lang{font-size:0.75rem;padding:1px 6px;border-radius:9999px;color:#fff;font-weight:600}
    .stars{color:#e3b341;font-size:0.8rem;white-space:nowrap}
    .summary{
      color:#8b949e;font-size:0.82rem;line-height:1.45;
      display:-webkit-box;-webkit-line-clamp:3;-webkit-box-orient:vertical;overflow:hidden;
      margin-top:0.15rem;
    }
    .summary.expanded{display:block;-webkit-line-clamp:unset}
    .show-more{
      color:#58a6ff;font-size:0.75rem;cursor:pointer;
      background:none;border:none;padding:0;margin-top:0.15rem;
    }
    .show-more:hover{text-decoration:underline}
    .footer{text-align:center;padding:1.5rem 1rem;color:#484f58;font-size:0.7rem;border-top:1px solid #21262d;margin-top:1rem}
  </style>
</head>
<body>

<div class="header">
  <h1>${report.projects.length} Trending Projects</h1>
  <div class="meta">
    <span>${date}</span>
    <span>·</span>
    <a href="${report.videoUrl}" target="_blank" rel="noopener">▶ Watch on YouTube</a>
    <span class="badge">${report.projects.length}</span>
  </div>
</div>

<div class="list" id="list"></div>

<div class="footer">Generated by github-awesome-monitor</div>

<script id="project-data" type="application/json">${projectsJson}</script>
<script id="lang-colors" type="application/json">${colorsJson}</script>

<script>
(function(){
  const projects = JSON.parse(document.getElementById('project-data').textContent);
  const colors = JSON.parse(document.getElementById('lang-colors').textContent);
  const list = document.getElementById('list');

  projects.forEach(function(p, i){
    const div = document.createElement('div');
    div.className = 'project';

    const top = document.createElement('div');
    top.className = 'project-top';

    const a = document.createElement('a');
    a.href = p.url;
    a.target = '_blank';
    a.rel = 'noopener';
    a.textContent = p.owner + '/' + p.repo;

    top.appendChild(a);

    if(p.language){
      const lang = document.createElement('span');
      lang.className = 'lang';
      lang.style.background = colors[p.language] || '#8b949e';
      lang.textContent = p.language;
      top.appendChild(lang);
    }

    if(p.stars != null){
      const s = document.createElement('span');
      s.className = 'stars';
      s.textContent = '★ ' + (p.stars >= 1000 ? (p.stars/1000).toFixed(1)+'k' : String(p.stars));
      top.appendChild(s);
    }

    div.appendChild(top);

    var summaryText = p.summary || p.description || '';
    if(summaryText){
      const sum = document.createElement('div');
      sum.className = 'summary';
      sum.textContent = summaryText;
      div.appendChild(sum);

      // Check if text is clamped (needs "show more")
      requestAnimationFrame(function(){
        if(sum.scrollHeight > sum.clientHeight + 2){
          const btn = document.createElement('button');
          btn.className = 'show-more';
          btn.textContent = 'Show more';
          btn.onclick = function(){
            sum.classList.toggle('expanded');
            btn.textContent = sum.classList.contains('expanded') ? 'Show less' : 'Show more';
          };
          div.appendChild(btn);
        }
      });
    }

    list.appendChild(div);
  });
})();
</script>
</body>
</html>`;
}
